### ISSUE TITLE
I can't download the CAD files 

### ISSUE THREAD

**Issue by Majed98kfupm** [XRobots/ServoSmoothing#3]
it shows like this when i want to open i
![WhatsApp Image 2021-10-03 at 4 59 14 PM](https://user-images.githubusercontent.com/91834448/135756987-1df2ce1e-af3d-4064-8230-7c7a47cdde3d.jpeg)
![WhatsApp Image 2021-10-03 at 4 59 28 PM](https://user-images.githubusercontent.com/91834448/135756989-aee20282-a339-4cd6-8089-663761f16633.jpeg)
t

**Comment by XRobots** [comment]
use the 'download zip' function

**Comment by Majed98kfupm** [comment]
I tried and it didn’t work for me.
Could you please send the zip file by email?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Majed98kfupm** [comment]
mjo0od_al-hajri@hotmail.com

**Comment by XRobots** [comment]
Click on the big green 'code button', then 'Download Zip' at the bottom
